######################################################################
# Automatically generated by qmake (3.0) Sun Mar 30 10:39:23 2014
######################################################################

QT += widgets
TEMPLATE = app
TARGET = sejtauto
INCLUDEPATH += .

# Input
HEADERS += sejtablak.h sejtszal.h
SOURCES += sejtablak.cpp sejtszal.cpp main.cpp
